name: Production Build and Deploy

on:
  push:
    branches: [ main ]

env:
  HOST_NAME: blog.vankoot.net

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify --baseUrl https://${{ env.HOST_NAME }}/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        cname: ${{ env.HOST_NAME }}
        publish_dir: ./public
        publish_branch: gh-pages
        allow_empty_commit: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
